{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}\r"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "DIsk Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "\r\nnode_filesystem_free_bytes{device=\"/dev/vda2\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" },
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  }
 ]
}